from django.db import models

# Create your models here.
# class graphBasedData(models.Model):
#     year = models.CharField(max_length = 5)
#     hocan = models.FloatField()
#     g1sb0 = models.FloatField()
#     corn = models.FloatField()
#     hsbo = models.FloatField()
#     stote_oil_blend = models.FloatField()
#     chicken_par_fry = models.FloatField()

class values(models.Model):
    hocan15 = models.FloatField(null=True)
    g1sb015 = models.FloatField(null=True)
    corn15 = models.FloatField(null=True)
    hsbo15 = models.FloatField(null=True)
    stote_oil_blend15 = models.FloatField(null=True)
    chicken_par_fry15 = models.FloatField(null=True)
    macd_system_total16 = models.FloatField(null=True)


    hocan16 = models.FloatField(null=True)
    g1sb016 = models.FloatField(null=True)
    corn16 = models.FloatField(null=True)
    hsbo16 = models.FloatField(null=True)
    stote_oil_blend16 = models.FloatField(null=True)
    chicken_par_fry16 = models.FloatField(null=True)
    macd_system_total16 = models.FloatField(null=True)

    hocan17 = models.FloatField(null=True)
    g1sb017 = models.FloatField(null=True)
    corn17 = models.FloatField(null=True)
    hsbo17 = models.FloatField(null=True)
    stote_oil_blend17 = models.FloatField(null=True)
    chicken_par_fry17 = models.FloatField(null=True)
    macd_system_total17 = models.FloatField(null=True)

    hocan18 = models.FloatField(null=True)
    g1sb018 = models.FloatField(null=True)
    corn18 = models.FloatField(null=True)
    hsbo18 = models.FloatField(null=True)
    stote_oil_blend18 = models.FloatField(null=True)
    chicken_par_fry18 = models.FloatField(null=True)
    macd_system_total18 = models.FloatField(null=True)

    hocan19 = models.FloatField(null=True)
    g1sb019 = models.FloatField(null=True)
    corn19 = models.FloatField(null=True)
    hsbo19 = models.FloatField(null=True)
    stote_oil_blend19 = models.FloatField(null=True)
    chicken_par_fry19 = models.FloatField(null=True)
    macd_system_total19 = models.FloatField(null=True)

    hocan20 = models.FloatField(null=True)
    g1sb020 = models.FloatField(null=True)
    corn20 = models.FloatField(null=True)
    hsbo20 = models.FloatField(null=True)
    stote_oil_blend20 = models.FloatField(null=True)
    chicken_par_fry20 = models.FloatField(null=True)
    macd_system_total20 = models.FloatField(null=True)

    hocan21 = models.FloatField(null=True)
    g1sb021 = models.FloatField(null=True)
    corn21 = models.FloatField(null=True)
    hsbo21 = models.FloatField(null=True)
    stote_oil_blend21 = models.FloatField(null=True)
    chicken_par_fry21 = models.FloatField(null=True)
    macd_system_total21 = models.FloatField(null=True)

    hocan22 = models.FloatField(null=True)
    g1sb022 = models.FloatField(null=True)
    corn22 = models.FloatField(null=True)
    hsbo22 = models.FloatField(null=True)
    stote_oil_blend22 = models.FloatField(null=True)
    chicken_par_fry22 = models.FloatField(null=True)
    macd_system_total22 = models.FloatField(null=True)

    hocan23 = models.FloatField(null=True)
    g1sb023 = models.FloatField(null=True)
    corn23 = models.FloatField(null=True)
    hsbo23 = models.FloatField(null=True)
    stote_oil_blend23 = models.FloatField(null=True)
    chicken_par_fry23 = models.FloatField(null=True)
    macd_system_total23 = models.FloatField(null=True)

    hocan24 = models.FloatField(null=True)
    g1sb024 = models.FloatField(null=True)
    corn24 = models.FloatField(null=True)
    hsbo24 = models.FloatField(null=True)
    stote_oil_blend24 = models.FloatField(null=True)
    chicken_par_fry24 = models.FloatField(null=True)
    macd_system_total24 = models.FloatField(null=True)

    rhpko15 = models.FloatField(null=True)
    rhpkol15 = models.FloatField(null=True)
    rhpkst15 = models.FloatField(null=True)
    shortening15 = models.FloatField(null=True)
    rhpo15 = models.FloatField(null=True)
    rpst15 = models.FloatField(null=True)
    rhpst15 = models.FloatField(null=True)
    rhcno15 = models.FloatField(null=True)
    rcno15 = models.FloatField(null=True)
    rpko15 = models.FloatField(null=True)
    subtotal15 = models.FloatField(null=True)

    rhpko16 = models.FloatField(null=True)
    rhpkol16 = models.FloatField(null=True)
    rhpkst16 = models.FloatField(null=True)
    shortening16 = models.FloatField(null=True)
    rhpo16 = models.FloatField(null=True)
    rpst16 = models.FloatField(null=True)
    rhpst16 = models.FloatField(null=True)
    rhcno16 = models.FloatField(null=True)
    rcno16 = models.FloatField(null=True)
    rpko16 = models.FloatField(null=True)
    subtotal16 = models.FloatField(null=True)

    rhpko17 = models.FloatField(null=True)
    rhpkol17 = models.FloatField(null=True)
    rhpkst17 = models.FloatField(null=True)
    shortening17 = models.FloatField(null=True)
    rhpo17 = models.FloatField(null=True)
    rpst17 = models.FloatField(null=True)
    rhpst17 = models.FloatField(null=True)
    rhcno17 = models.FloatField(null=True)
    rcno17 = models.FloatField(null=True)
    rpko17 = models.FloatField(null=True)
    subtotal17 = models.FloatField(null=True)

    rhpko18 = models.FloatField(null=True)
    rhpkol18 = models.FloatField(null=True)
    rhpkst18 = models.FloatField(null=True)
    shortening18 = models.FloatField(null=True)
    rhpo18 = models.FloatField(null=True)
    rpst18 = models.FloatField(null=True)
    rhpst18 = models.FloatField(null=True)
    rhcno18 = models.FloatField(null=True)
    rcno18 = models.FloatField(null=True)
    rpko18 = models.FloatField(null=True)
    subtotal18 = models.FloatField(null=True)

    rhpko19 = models.FloatField(null=True)
    rhpkol19 = models.FloatField(null=True)
    rhpkst19 = models.FloatField(null=True)
    shortening19 = models.FloatField(null=True)
    rhpo19 = models.FloatField(null=True)
    rpst19 = models.FloatField(null=True)
    rhpst19 = models.FloatField(null=True)
    rhcno19 = models.FloatField(null=True)
    rcno19 = models.FloatField(null=True)
    rpko19 = models.FloatField(null=True)
    subtotal19 = models.FloatField(null=True)

    rhpko20 = models.FloatField(null=True)
    rhpkol20 = models.FloatField(null=True)
    rhpkst20 = models.FloatField(null=True)
    shortening20 = models.FloatField(null=True)
    rhpo20 = models.FloatField(null=True)
    rpst20 = models.FloatField(null=True)
    rhpst20 = models.FloatField(null=True)
    rhcno20 = models.FloatField(null=True)
    rcno20 = models.FloatField(null=True)
    rpko20 = models.FloatField(null=True)
    subtotal20 = models.FloatField(null=True)

    rhpko21 = models.FloatField(null=True)
    rhpkol21 = models.FloatField(null=True)
    rhpkst21 = models.FloatField(null=True)
    shortening21 = models.FloatField(null=True)
    rhpo21 = models.FloatField(null=True)
    rpst21 = models.FloatField(null=True)
    rhpst21 = models.FloatField(null=True)
    rhcno21 = models.FloatField(null=True)
    rcno21 = models.FloatField(null=True)
    rpko21 = models.FloatField(null=True)
    subtotal21 = models.FloatField(null=True)

    rhpko22 = models.FloatField(null=True)
    rhpkol22 = models.FloatField(null=True)
    rhpkst22 = models.FloatField(null=True)
    shortening22 = models.FloatField(null=True)
    rhpo22 = models.FloatField(null=True)
    rpst22 = models.FloatField(null=True)
    rhpst22 = models.FloatField(null=True)
    rhcno22 = models.FloatField(null=True)
    rcno22 = models.FloatField(null=True)
    rpko22 = models.FloatField(null=True)
    subtotal22 = models.FloatField(null=True)

    rhpko23 = models.FloatField(null=True)
    rhpkol23 = models.FloatField(null=True)
    rhpkst23 = models.FloatField(null=True)
    shortening23 = models.FloatField(null=True)
    rhpo23 = models.FloatField(null=True)
    rpst23 = models.FloatField(null=True)
    rhpst23 = models.FloatField(null=True)
    rhcno23 = models.FloatField(null=True)
    rcno23 = models.FloatField(null=True)
    rpko23 = models.FloatField(null=True)
    subtotal23 = models.FloatField(null=True)

    rhpko24 = models.FloatField(null=True)
    rhpkol24 = models.FloatField(null=True)
    rhpkst24 = models.FloatField(null=True)
    shortening24 = models.FloatField(null=True)
    rhpo24 = models.FloatField(null=True)
    rpst24 = models.FloatField(null=True)
    rhpst24 = models.FloatField(null=True)
    rhcno24 = models.FloatField(null=True)
    rcno24 = models.FloatField(null=True)
    rpko24 = models.FloatField(null=True)
    subtotal24 = models.FloatField(null=True)

    apshortening15 = models.FloatField(null=True)
    apshortening16 = models.FloatField(null=True)
    apshortening17 = models.FloatField(null=True)
    apshortening18 = models.FloatField(null=True)
    apshortening19 = models.FloatField(null=True)
    apshortening20 = models.FloatField(null=True)
    apshortening21 = models.FloatField(null=True)
    apshortening22 = models.FloatField(null=True)
    apshortening23 = models.FloatField(null=True)
    apshortening24 = models.FloatField(null=True)

    rhpo15 = models.FloatField(null=True)
    rhpo16 = models.FloatField(null=True)
    rhpo17 = models.FloatField(null=True)
    rhpo18 = models.FloatField(null=True)
    rhpo19 = models.FloatField(null=True)
    rhpo20 = models.FloatField(null=True)
    rhpo21 = models.FloatField(null=True)
    rhpo22 = models.FloatField(null=True)
    rhpo23 = models.FloatField(null=True)
    rhpo24 = models.FloatField(null=True)

    rhsbo15 = models.FloatField(null=True)
    rhsbo16 = models.FloatField(null=True)
    rhsbo17 = models.FloatField(null=True)
    rhsbo18 = models.FloatField(null=True)
    rhsbo19 = models.FloatField(null=True)
    rhsbo20 = models.FloatField(null=True)
    rhsbo21 = models.FloatField(null=True)
    rhsbo22 = models.FloatField(null=True)
    rhsbo23 = models.FloatField(null=True)
    rhsbo24 = models.FloatField(null=True)

    subtotal_15 = models.FloatField(null=True)
    subtotal_16 = models.FloatField(null=True)
    subtotal_17 = models.FloatField(null=True)
    subtotal_18 = models.FloatField(null=True)
    subtotal_19 = models.FloatField(null=True)
    subtotal_20 = models.FloatField(null=True)
    subtotal_21 = models.FloatField(null=True)
    subtotal_22 = models.FloatField(null=True)
    subtotal_23 = models.FloatField(null=True)
    subtotal_24 = models.FloatField(null=True)

    sf_total15 = models.FloatField(null=True)
    sf_total16 = models.FloatField(null=True)
    sf_total17 = models.FloatField(null=True)
    sf_total18 = models.FloatField(null=True)
    sf_total19 = models.FloatField(null=True)
    sf_total20 = models.FloatField(null=True)
    sf_total21 = models.FloatField(null=True)
    sf_total22 = models.FloatField(null=True)
    sf_total23 = models.FloatField(null=True)
    sf_total24 = models.FloatField(null=True)

    g1sbo15 = models.FloatField(null=True)
    g1sbo16 = models.FloatField(null=True)
    g1sbo17 = models.FloatField(null=True)
    g1sbo18 = models.FloatField(null=True)
    g1sbo19 = models.FloatField(null=True)
    g1sbo20 = models.FloatField(null=True)
    g1sbo21 = models.FloatField(null=True)
    g1sbo22 = models.FloatField(null=True)
    g1sbo23 = models.FloatField(null=True)
    g1sbo24 = models.FloatField(null=True)

    blendedoil15 = models.FloatField(null=True)
    blendedoil16 = models.FloatField(null=True)
    blendedoil17 = models.FloatField(null=True)
    blendedoil18 = models.FloatField(null=True)
    blendedoil19 = models.FloatField(null=True)
    blendedoil20 = models.FloatField(null=True)
    blendedoil21 = models.FloatField(null=True)
    blendedoil22 = models.FloatField(null=True)
    blendedoil23 = models.FloatField(null=True)
    blendedoil24 = models.FloatField(null=True)

    rol15 = models.FloatField(null=True)
    rol16 = models.FloatField(null=True)
    rol17 = models.FloatField(null=True)
    rol18 = models.FloatField(null=True)
    rol19 = models.FloatField(null=True)
    rol20 = models.FloatField(null=True)
    rol21 = models.FloatField(null=True)
    rol22 = models.FloatField(null=True)
    rol23 = models.FloatField(null=True)
    rol24 = models.FloatField(null=True)

    spmf15 = models.FloatField(null=True)
    spmf16 = models.FloatField(null=True)
    spmf17 = models.FloatField(null=True)
    spmf18 = models.FloatField(null=True)
    spmf19 = models.FloatField(null=True)
    spmf20 = models.FloatField(null=True)
    spmf21 = models.FloatField(null=True)
    spmf22 = models.FloatField(null=True)
    spmf23 = models.FloatField(null=True)
    spmf24 = models.FloatField(null=True)

    mpbtotal15 = models.FloatField(null=True)
    mpbtotal16 = models.FloatField(null=True)
    mpbtotal17 = models.FloatField(null=True)
    mpbtotal18 = models.FloatField(null=True)
    mpbtotal19 = models.FloatField(null=True)
    mpbtotal20 = models.FloatField(null=True)
    mpbtotal21 = models.FloatField(null=True)
    mpbtotal22 = models.FloatField(null=True)
    mpbtotal23 = models.FloatField(null=True)
    mpbtotal24 = models.FloatField(null=True)

    g1sbo1_15 = models.FloatField(null=True)
    g1sbo1_16 = models.FloatField(null=True)
    g1sbo1_17 = models.FloatField(null=True)
    g1sbo1_18 = models.FloatField(null=True)
    g1sbo1_19 = models.FloatField(null=True)
    g1sbo1_20 = models.FloatField(null=True)
    g1sbo1_21 = models.FloatField(null=True)
    g1sbo1_22 = models.FloatField(null=True)
    g1sbo1_23 = models.FloatField(null=True)
    g1sbo1_24 = models.FloatField(null=True)

    g1sbo2_15 = models.FloatField(null=True)
    g1sbo2_16 = models.FloatField(null=True)
    g1sbo2_17 = models.FloatField(null=True)
    g1sbo2_18 = models.FloatField(null=True)
    g1sbo2_19 = models.FloatField(null=True)
    g1sbo2_20 = models.FloatField(null=True)
    g1sbo2_21 = models.FloatField(null=True)
    g1sbo2_22 = models.FloatField(null=True)
    g1sbo2_23 = models.FloatField(null=True)
    g1sbo2_24 = models.FloatField(null=True)

    g1sbo3_15 = models.FloatField(null=True)
    g1sbo3_16 = models.FloatField(null=True)
    g1sbo3_17 = models.FloatField(null=True)
    g1sbo3_18 = models.FloatField(null=True)
    g1sbo3_19 = models.FloatField(null=True)
    g1sbo3_20 = models.FloatField(null=True)
    g1sbo3_21 = models.FloatField(null=True)
    g1sbo3_22 = models.FloatField(null=True)
    g1sbo3_23 = models.FloatField(null=True)
    g1sbo3_24 = models.FloatField(null=True)

    g1sbo4_15 = models.FloatField(null=True)
    g1sbo4_16 = models.FloatField(null=True)
    g1sbo4_17 = models.FloatField(null=True)
    g1sbo4_18 = models.FloatField(null=True)
    g1sbo4_19 = models.FloatField(null=True)
    g1sbo4_20 = models.FloatField(null=True)
    g1sbo4_21 = models.FloatField(null=True)
    g1sbo4_22 = models.FloatField(null=True)
    g1sbo4_23 = models.FloatField(null=True)
    g1sbo4_24 = models.FloatField(null=True)

    blendedoil1_15 = models.FloatField(null=True)
    blendedoil1_16 = models.FloatField(null=True)
    blendedoil1_17 = models.FloatField(null=True)
    blendedoil1_18 = models.FloatField(null=True)
    blendedoil1_19 = models.FloatField(null=True)
    blendedoil1_20 = models.FloatField(null=True)
    blendedoil1_21 = models.FloatField(null=True)
    blendedoil1_22 = models.FloatField(null=True)
    blendedoil1_23 = models.FloatField(null=True)
    blendedoil1_24 = models.FloatField(null=True)

    blendedoil2_15 = models.FloatField(null=True)
    blendedoil2_16 = models.FloatField(null=True)
    blendedoil2_17 = models.FloatField(null=True)
    blendedoil2_18 = models.FloatField(null=True)
    blendedoil2_19 = models.FloatField(null=True)
    blendedoil2_20 = models.FloatField(null=True)
    blendedoil2_21 = models.FloatField(null=True)
    blendedoil2_22 = models.FloatField(null=True)
    blendedoil2_23 = models.FloatField(null=True)
    blendedoil2_24 = models.FloatField(null=True)

    blendedoil3_15 = models.FloatField(null=True)
    blendedoil3_16 = models.FloatField(null=True)
    blendedoil3_17 = models.FloatField(null=True)
    blendedoil3_18 = models.FloatField(null=True)
    blendedoil3_19 = models.FloatField(null=True)
    blendedoil3_20 = models.FloatField(null=True)
    blendedoil3_21 = models.FloatField(null=True)
    blendedoil3_22 = models.FloatField(null=True)
    blendedoil3_23 = models.FloatField(null=True)
    blendedoil3_24 = models.FloatField(null=True)

    blendedoil4_15 = models.FloatField(null=True)
    blendedoil4_16 = models.FloatField(null=True)
    blendedoil4_17 = models.FloatField(null=True)
    blendedoil4_18 = models.FloatField(null=True)
    blendedoil4_19 = models.FloatField(null=True)
    blendedoil4_20 = models.FloatField(null=True)
    blendedoil4_21 = models.FloatField(null=True)
    blendedoil4_22 = models.FloatField(null=True)
    blendedoil4_23 = models.FloatField(null=True)
    blendedoil4_24 = models.FloatField(null=True)

    superolein1_15 = models.FloatField(null=True)
    superolein1_16 = models.FloatField(null=True)
    superolein1_17 = models.FloatField(null=True)
    superolein1_18 = models.FloatField(null=True)
    superolein1_19 = models.FloatField(null=True)
    superolein1_20 = models.FloatField(null=True)
    superolein1_21 = models.FloatField(null=True)
    superolein1_22 = models.FloatField(null=True)
    superolein1_23 = models.FloatField(null=True)
    superolein1_24 = models.FloatField(null=True)

    superolein2_15 = models.FloatField(null=True)
    superolein2_16 = models.FloatField(null=True)
    superolein2_17 = models.FloatField(null=True)
    superolein2_18 = models.FloatField(null=True)
    superolein2_19 = models.FloatField(null=True)
    superolein2_20 = models.FloatField(null=True)
    superolein2_21 = models.FloatField(null=True)
    superolein2_22 = models.FloatField(null=True)
    superolein2_23 = models.FloatField(null=True)
    superolein2_24 = models.FloatField(null=True)

    superolein3_15 = models.FloatField(null=True)
    superolein3_16 = models.FloatField(null=True)
    superolein3_17 = models.FloatField(null=True)
    superolein3_18 = models.FloatField(null=True)
    superolein3_19 = models.FloatField(null=True)
    superolein3_20 = models.FloatField(null=True)
    superolein3_21 = models.FloatField(null=True)
    superolein3_22 = models.FloatField(null=True)
    superolein3_23 = models.FloatField(null=True)
    superolein3_24 = models.FloatField(null=True)

    superolein4_15 = models.FloatField(null=True)
    superolein4_16 = models.FloatField(null=True)
    superolein4_17 = models.FloatField(null=True)
    superolein4_18 = models.FloatField(null=True)
    superolein4_19 = models.FloatField(null=True)
    superolein4_20 = models.FloatField(null=True)
    superolein4_21 = models.FloatField(null=True)
    superolein4_22 = models.FloatField(null=True)
    superolein4_23 = models.FloatField(null=True)
    superolein4_24 = models.FloatField(null=True)

    mpptotal15 = models.FloatField(null=True)
    mpptotal16 = models.FloatField(null=True)
    mpptotal17 = models.FloatField(null=True)
    mpptotal18 = models.FloatField(null=True)
    mpptotal19 = models.FloatField(null=True)
    mpptotal20 = models.FloatField(null=True)
    mpptotal21 = models.FloatField(null=True)
    mpptotal22 = models.FloatField(null=True)
    mpptotal23 = models.FloatField(null=True)
    mpptotal24 = models.FloatField(null=True)

    ls15 = models.FloatField(null=True)
    ls16 = models.FloatField(null=True)
    ls17 = models.FloatField(null=True)
    ls18 = models.FloatField(null=True)
    ls19 = models.FloatField(null=True)
    ls20 = models.FloatField(null=True)
    ls21 = models.FloatField(null=True)
    ls22 = models.FloatField(null=True)
    ls23 = models.FloatField(null=True)
    ls24 = models.FloatField(null=True)

    nis15 = models.FloatField(null=True)
    nis16 = models.FloatField(null=True)
    nis17 = models.FloatField(null=True)
    nis18 = models.FloatField(null=True)
    nis19 = models.FloatField(null=True)
    nis20 = models.FloatField(null=True)
    nis21 = models.FloatField(null=True)
    nis22 = models.FloatField(null=True)
    nis23 = models.FloatField(null=True)
    nis24 = models.FloatField(null=True)

    nim15 = models.FloatField(null=True)
    nim16 = models.FloatField(null=True)
    nim17 = models.FloatField(null=True)
    nim18 = models.FloatField(null=True)
    nim19 = models.FloatField(null=True)
    nim20 = models.FloatField(null=True)
    nim21 = models.FloatField(null=True)
    nim22 = models.FloatField(null=True)
    nim23 = models.FloatField(null=True)
    nim24 = models.FloatField(null=True)

    is15 = models.FloatField(null=True)
    is16 = models.FloatField(null=True)
    is17 = models.FloatField(null=True)
    is18 = models.FloatField(null=True)
    is19 = models.FloatField(null=True)
    is20 = models.FloatField(null=True)
    is21 = models.FloatField(null=True)
    is22 = models.FloatField(null=True)
    is23 = models.FloatField(null=True)
    is24 = models.FloatField(null=True)

    im15 = models.FloatField(null=True)
    im16 = models.FloatField(null=True)
    im17 = models.FloatField(null=True)
    im18 = models.FloatField(null=True)
    im19 = models.FloatField(null=True)
    im20 = models.FloatField(null=True)
    im21 = models.FloatField(null=True)
    im22 = models.FloatField(null=True)
    im23 = models.FloatField(null=True)
    im24 = models.FloatField(null=True)

    asm15 = models.FloatField(null=True)
    asm16 = models.FloatField(null=True)
    asm17 = models.FloatField(null=True)
    asm18 = models.FloatField(null=True)
    asm19 = models.FloatField(null=True)
    asm20 = models.FloatField(null=True)
    asm21 = models.FloatField(null=True)
    asm22 = models.FloatField(null=True)
    asm23 = models.FloatField(null=True)
    asm24 = models.FloatField(null=True)

    bot15 = models.FloatField(null=True)
    bot16 = models.FloatField(null=True)
    bot17 = models.FloatField(null=True)
    bot18 = models.FloatField(null=True)
    bot19 = models.FloatField(null=True)
    bot20 = models.FloatField(null=True)
    bot21 = models.FloatField(null=True)
    bot22 = models.FloatField(null=True)
    bot23 = models.FloatField(null=True)
    bot24 = models.FloatField(null=True)

    tvp15 = models.FloatField(null=True)
    tvp16 = models.FloatField(null=True)
    tvp17 = models.FloatField(null=True)
    tvp18 = models.FloatField(null=True)
    tvp19 = models.FloatField(null=True)
    tvp20 = models.FloatField(null=True)
    tvp21 = models.FloatField(null=True)
    tvp22 = models.FloatField(null=True)
    tvp23 = models.FloatField(null=True)
    tvp24 = models.FloatField(null=True)

    bulk15 = models.FloatField(null=True)
    bulk16 = models.FloatField(null=True)
    bulk17 = models.FloatField(null=True)
    bulk18 = models.FloatField(null=True)
    bulk19 = models.FloatField(null=True)
    bulk20 = models.FloatField(null=True)
    bulk21 = models.FloatField(null=True)
    bulk22 = models.FloatField(null=True)
    bulk23 = models.FloatField(null=True)
    bulk24 = models.FloatField(null=True)

    packaged15 = models.FloatField(null=True)
    packaged16 = models.FloatField(null=True)
    packaged17 = models.FloatField(null=True)
    packaged18 = models.FloatField(null=True)
    packaged19 = models.FloatField(null=True)
    packaged20 = models.FloatField(null=True)
    packaged21 = models.FloatField(null=True)
    packaged22 = models.FloatField(null=True)
    packaged23 = models.FloatField(null=True)
    packaged24 = models.FloatField(null=True)

    sob_n15 = models.FloatField(null=True)
    sob_n16 = models.FloatField(null=True)
    sob_n17 = models.FloatField(null=True)
    sob_n18 = models.FloatField(null=True)
    sob_n19 = models.FloatField(null=True)
    sob_n20 = models.FloatField(null=True)
    sob_n21 = models.FloatField(null=True)
    sob_n22 = models.FloatField(null=True)
    sob_n23 = models.FloatField(null=True)
    sob_n24 = models.FloatField(null=True)

    cpf_n15 = models.FloatField(null=True)
    cpf_n16 = models.FloatField(null=True)
    cpf_n17 = models.FloatField(null=True)
    cpf_n18 = models.FloatField(null=True)
    cpf_n19 = models.FloatField(null=True)
    cpf_n20 = models.FloatField(null=True)
    cpf_n21 = models.FloatField(null=True)
    cpf_n22 = models.FloatField(null=True)
    cpf_n23 = models.FloatField(null=True)
    cpf_n24 = models.FloatField(null=True)

    sob_d15 = models.FloatField(null=True)
    sob_d16 = models.FloatField(null=True)
    sob_d17 = models.FloatField(null=True)
    sob_d18 = models.FloatField(null=True)
    sob_d19 = models.FloatField(null=True)
    sob_d20 = models.FloatField(null=True)
    sob_d21 = models.FloatField(null=True)
    sob_d22 = models.FloatField(null=True)
    sob_d23 = models.FloatField(null=True)
    sob_d24 = models.FloatField(null=True)

    cpf_d15 = models.FloatField(null=True)
    cpf_d16 = models.FloatField(null=True)
    cpf_d17 = models.FloatField(null=True)
    cpf_d18 = models.FloatField(null=True)
    cpf_d19 = models.FloatField(null=True)
    cpf_d20 = models.FloatField(null=True)
    cpf_d21 = models.FloatField(null=True)
    cpf_d22 = models.FloatField(null=True)
    cpf_d23 = models.FloatField(null=True)
    cpf_d24 = models.FloatField(null=True)

    sob_fr15 = models.FloatField(null=True)
    sob_fr16 = models.FloatField(null=True)
    sob_fr17 = models.FloatField(null=True)
    sob_fr18 = models.FloatField(null=True)
    sob_fr19 = models.FloatField(null=True)
    sob_fr20 = models.FloatField(null=True)
    sob_fr21 = models.FloatField(null=True)
    sob_fr22 = models.FloatField(null=True)
    sob_fr23 = models.FloatField(null=True)
    sob_fr24 = models.FloatField(null=True)

    cpf_fr15 = models.FloatField(null=True)
    cpf_fr16 = models.FloatField(null=True)
    cpf_fr17 = models.FloatField(null=True)
    cpf_fr18 = models.FloatField(null=True)
    cpf_fr19 = models.FloatField(null=True)
    cpf_fr20 = models.FloatField(null=True)
    cpf_fr21 = models.FloatField(null=True)
    cpf_fr22 = models.FloatField(null=True)
    cpf_fr23 = models.FloatField(null=True)
    cpf_fr24 = models.FloatField(null=True)

    sob_h15 = models.FloatField(null=True)
    sob_h16 = models.FloatField(null=True)
    sob_h17 = models.FloatField(null=True)
    sob_h18 = models.FloatField(null=True)
    sob_h19 = models.FloatField(null=True)
    sob_h20 = models.FloatField(null=True)
    sob_h21 = models.FloatField(null=True)
    sob_h22 = models.FloatField(null=True)
    sob_h23 = models.FloatField(null=True)
    sob_h24 = models.FloatField(null=True)

    sob_perf15 = models.FloatField(null=True)
    sob_perf16 = models.FloatField(null=True)
    sob_perf17 = models.FloatField(null=True)
    sob_perf18 = models.FloatField(null=True)
    sob_perf19 = models.FloatField(null=True)
    sob_perf20 = models.FloatField(null=True)
    sob_perf21 = models.FloatField(null=True)
    sob_perf22 = models.FloatField(null=True)
    sob_perf23 = models.FloatField(null=True)
    sob_perf24 = models.FloatField(null=True)

    cpf_lv15 = models.FloatField(null=True)
    cpf_lv16 = models.FloatField(null=True)
    cpf_lv17 = models.FloatField(null=True)
    cpf_lv18 = models.FloatField(null=True)
    cpf_lv19 = models.FloatField(null=True)
    cpf_lv20 = models.FloatField(null=True)
    cpf_lv21 = models.FloatField(null=True)
    cpf_lv22 = models.FloatField(null=True)
    cpf_lv23 = models.FloatField(null=True)
    cpf_lv24 = models.FloatField(null=True)

    cbibv15 = models.FloatField(null=True)
    cbibv16 = models.FloatField(null=True)
    cbibv17 = models.FloatField(null=True)
    cbibv18 = models.FloatField(null=True)
    cbibv19 = models.FloatField(null=True)
    cbibv20 = models.FloatField(null=True)
    cbibv21 = models.FloatField(null=True)
    cbibv22 = models.FloatField(null=True)
    cbibv23 = models.FloatField(null=True)
    cbibv24 = models.FloatField(null=True)

    cbibv_gsbo15 = models.FloatField(null=True)
    cbibv_gsbo16 = models.FloatField(null=True)
    cbibv_gsbo17 = models.FloatField(null=True)
    cbibv_gsbo18 = models.FloatField(null=True)
    cbibv_gsbo19 = models.FloatField(null=True)
    cbibv_gsbo20 = models.FloatField(null=True)
    cbibv_gsbo21 = models.FloatField(null=True)
    cbibv_gsbo22 = models.FloatField(null=True)
    cbibv_gsbo23 = models.FloatField(null=True)
    cbibv_gsbo24 = models.FloatField(null=True)

    cbibv_blenedoil15 = models.FloatField(null=True)
    cbibv_blenedoil16 = models.FloatField(null=True)
    cbibv_blenedoil17 = models.FloatField(null=True)
    cbibv_blenedoil18 = models.FloatField(null=True)
    cbibv_blenedoil19 = models.FloatField(null=True)
    cbibv_blenedoil20 = models.FloatField(null=True)
    cbibv_blenedoil21 = models.FloatField(null=True)
    cbibv_blenedoil22 = models.FloatField(null=True)
    cbibv_blenedoil23 = models.FloatField(null=True)
    cbibv_blenedoil24 = models.FloatField(null=True)

    cbibv_rol15 = models.FloatField(null=True)
    cbibv_rol16 = models.FloatField(null=True)
    cbibv_rol17 = models.FloatField(null=True)
    cbibv_rol18 = models.FloatField(null=True)
    cbibv_rol19 = models.FloatField(null=True)
    cbibv_rol20 = models.FloatField(null=True)
    cbibv_rol21 = models.FloatField(null=True)
    cbibv_rol22 = models.FloatField(null=True)
    cbibv_rol23 = models.FloatField(null=True)
    cbibv_rol24 = models.FloatField(null=True)

    cbibv_spmf15 = models.FloatField(null=True)
    cbibv_spmf16 = models.FloatField(null=True)
    cbibv_spmf17 = models.FloatField(null=True)
    cbibv_spmf18 = models.FloatField(null=True)
    cbibv_spmf19 = models.FloatField(null=True)
    cbibv_spmf20 = models.FloatField(null=True)
    cbibv_spmf21 = models.FloatField(null=True)
    cbibv_spmf22 = models.FloatField(null=True)
    cbibv_spmf23 = models.FloatField(null=True)
    cbibv_spmf24 = models.FloatField(null=True)

    cpetv15 = models.FloatField(null=True)
    cpetv16 = models.FloatField(null=True)
    cpetv17 = models.FloatField(null=True)
    cpetv18 = models.FloatField(null=True)
    cpetv19 = models.FloatField(null=True)
    cpetv20 = models.FloatField(null=True)
    cpetv21 = models.FloatField(null=True)
    cpetv22 = models.FloatField(null=True)
    cpetv23 = models.FloatField(null=True)
    cpetv24 = models.FloatField(null=True)

    cpetv_gsbo1_15 = models.FloatField(null=True)
    cpetv_gsbo1_16 = models.FloatField(null=True)
    cpetv_gsbo1_17 = models.FloatField(null=True)
    cpetv_gsbo1_18 = models.FloatField(null=True)
    cpetv_gsbo1_19 = models.FloatField(null=True)
    cpetv_gsbo1_20 = models.FloatField(null=True)
    cpetv_gsbo1_21 = models.FloatField(null=True)
    cpetv_gsbo1_22 = models.FloatField(null=True)
    cpetv_gsbo1_23 = models.FloatField(null=True)
    cpetv_gsbo1_24 = models.FloatField(null=True)

    cpetv_gsbo2_15 = models.FloatField(null=True)
    cpetv_gsbo2_16 = models.FloatField(null=True)
    cpetv_gsbo2_17 = models.FloatField(null=True)
    cpetv_gsbo2_18 = models.FloatField(null=True)
    cpetv_gsbo2_19 = models.FloatField(null=True)
    cpetv_gsbo2_20 = models.FloatField(null=True)
    cpetv_gsbo2_21 = models.FloatField(null=True)
    cpetv_gsbo2_22 = models.FloatField(null=True)
    cpetv_gsbo2_23 = models.FloatField(null=True)
    cpetv_gsbo2_24 = models.FloatField(null=True)

    cpetv_gsbo3_15 = models.FloatField(null=True)
    cpetv_gsbo3_16 = models.FloatField(null=True)
    cpetv_gsbo3_17 = models.FloatField(null=True)
    cpetv_gsbo3_18 = models.FloatField(null=True)
    cpetv_gsbo3_19 = models.FloatField(null=True)
    cpetv_gsbo3_20 = models.FloatField(null=True)
    cpetv_gsbo3_21 = models.FloatField(null=True)
    cpetv_gsbo3_22 = models.FloatField(null=True)
    cpetv_gsbo3_23 = models.FloatField(null=True)
    cpetv_gsbo3_24 = models.FloatField(null=True)

    cpetv_gsbo4_15 = models.FloatField(null=True)
    cpetv_gsbo4_16 = models.FloatField(null=True)
    cpetv_gsbo4_17 = models.FloatField(null=True)
    cpetv_gsbo4_18 = models.FloatField(null=True)
    cpetv_gsbo4_19 = models.FloatField(null=True)
    cpetv_gsbo4_20 = models.FloatField(null=True)
    cpetv_gsbo4_21 = models.FloatField(null=True)
    cpetv_gsbo4_22 = models.FloatField(null=True)
    cpetv_gsbo4_23 = models.FloatField(null=True)
    cpetv_gsbo4_24 = models.FloatField(null=True)

    cpetv_blendedoil1_15 = models.FloatField(null=True)
    cpetv_blendedoil1_16 = models.FloatField(null=True)
    cpetv_blendedoil1_17 = models.FloatField(null=True)
    cpetv_blendedoil1_18 = models.FloatField(null=True)
    cpetv_blendedoil1_19 = models.FloatField(null=True)
    cpetv_blendedoil1_20 = models.FloatField(null=True)
    cpetv_blendedoil1_21 = models.FloatField(null=True)
    cpetv_blendedoil1_22 = models.FloatField(null=True)
    cpetv_blendedoil1_23 = models.FloatField(null=True)
    cpetv_blendedoil1_24 = models.FloatField(null=True)

    cpetv_blendedoil2_15 = models.FloatField(null=True)
    cpetv_blendedoil2_16 = models.FloatField(null=True)
    cpetv_blendedoil2_17 = models.FloatField(null=True)
    cpetv_blendedoil2_18 = models.FloatField(null=True)
    cpetv_blendedoil2_19 = models.FloatField(null=True)
    cpetv_blendedoil2_20 = models.FloatField(null=True)
    cpetv_blendedoil2_21 = models.FloatField(null=True)
    cpetv_blendedoil2_22 = models.FloatField(null=True)
    cpetv_blendedoil2_23 = models.FloatField(null=True)
    cpetv_blendedoil2_24 = models.FloatField(null=True)

    cpetv_blendedoil3_15 = models.FloatField(null=True)
    cpetv_blendedoil3_16 = models.FloatField(null=True)
    cpetv_blendedoil3_17 = models.FloatField(null=True)
    cpetv_blendedoil3_18 = models.FloatField(null=True)
    cpetv_blendedoil3_19 = models.FloatField(null=True)
    cpetv_blendedoil3_20 = models.FloatField(null=True)
    cpetv_blendedoil3_21 = models.FloatField(null=True)
    cpetv_blendedoil3_22 = models.FloatField(null=True)
    cpetv_blendedoil3_23 = models.FloatField(null=True)
    cpetv_blendedoil3_24 = models.FloatField(null=True)

    cpetv_blendedoil4_15 = models.FloatField(null=True)
    cpetv_blendedoil4_16 = models.FloatField(null=True)
    cpetv_blendedoil4_17 = models.FloatField(null=True)
    cpetv_blendedoil4_18 = models.FloatField(null=True)
    cpetv_blendedoil4_19 = models.FloatField(null=True)
    cpetv_blendedoil4_20 = models.FloatField(null=True)
    cpetv_blendedoil4_21 = models.FloatField(null=True)
    cpetv_blendedoil4_22 = models.FloatField(null=True)
    cpetv_blendedoil4_23 = models.FloatField(null=True)
    cpetv_blendedoil4_24 = models.FloatField(null=True)

    cpetv_superolein1_15 = models.FloatField(null=True)
    cpetv_superolein1_16 = models.FloatField(null=True)
    cpetv_superolein1_17 = models.FloatField(null=True)
    cpetv_superolein1_18 = models.FloatField(null=True)
    cpetv_superolein1_19 = models.FloatField(null=True)
    cpetv_superolein1_20 = models.FloatField(null=True)
    cpetv_superolein1_21 = models.FloatField(null=True)
    cpetv_superolein1_22 = models.FloatField(null=True)
    cpetv_superolein1_23 = models.FloatField(null=True)
    cpetv_superolein1_24 = models.FloatField(null=True)

    cpetv_superolein2_15 = models.FloatField(null=True)
    cpetv_superolein2_16 = models.FloatField(null=True)
    cpetv_superolein2_17 = models.FloatField(null=True)
    cpetv_superolein2_18 = models.FloatField(null=True)
    cpetv_superolein2_19 = models.FloatField(null=True)
    cpetv_superolein2_20 = models.FloatField(null=True)
    cpetv_superolein2_21 = models.FloatField(null=True)
    cpetv_superolein2_22 = models.FloatField(null=True)
    cpetv_superolein2_23 = models.FloatField(null=True)
    cpetv_superolein2_24 = models.FloatField(null=True)

    cpetv_superolein3_15 = models.FloatField(null=True)
    cpetv_superolein3_16 = models.FloatField(null=True)
    cpetv_superolein3_17 = models.FloatField(null=True)
    cpetv_superolein3_18 = models.FloatField(null=True)
    cpetv_superolein3_19 = models.FloatField(null=True)
    cpetv_superolein3_20 = models.FloatField(null=True)
    cpetv_superolein3_21 = models.FloatField(null=True)
    cpetv_superolein3_22 = models.FloatField(null=True)
    cpetv_superolein3_23 = models.FloatField(null=True)
    cpetv_superolein3_24 = models.FloatField(null=True)

    cpetv_superolein4_15 = models.FloatField(null=True)
    cpetv_superolein4_16 = models.FloatField(null=True)
    cpetv_superolein4_17 = models.FloatField(null=True)
    cpetv_superolein4_18 = models.FloatField(null=True)
    cpetv_superolein4_19 = models.FloatField(null=True)
    cpetv_superolein4_20 = models.FloatField(null=True)
    cpetv_superolein4_21 = models.FloatField(null=True)
    cpetv_superolein4_22 = models.FloatField(null=True)
    cpetv_superolein4_23 = models.FloatField(null=True)
    cpetv_superolein4_24 = models.FloatField(null=True)

    mpbest15 = models.FloatField(null=True)
    mpbest16 = models.FloatField(null=True)
    mpbest17 = models.FloatField(null=True)
    mpbest18 = models.FloatField(null=True)
    mpbest19 = models.FloatField(null=True)
    mpbest20 = models.FloatField(null=True)
    mpbest21 = models.FloatField(null=True)
    mpbest22 = models.FloatField(null=True)
    mpbest23 = models.FloatField(null=True)
    mpbest24 = models.FloatField(null=True)

    mpbuis15 = models.FloatField(null=True)
    mpbuis16 = models.FloatField(null=True)
    mpbuis17 = models.FloatField(null=True)
    mpbuis18 = models.FloatField(null=True)
    mpbuis19 = models.FloatField(null=True)
    mpbuis20 = models.FloatField(null=True)
    mpbuis21 = models.FloatField(null=True)
    mpbuis22 = models.FloatField(null=True)
    mpbuis23 = models.FloatField(null=True)
    mpbuis24 = models.FloatField(null=True)

    pet15 = models.FloatField(null=True)
    pet16 = models.FloatField(null=True)
    pet17 = models.FloatField(null=True)
    pet18 = models.FloatField(null=True)
    pet19 = models.FloatField(null=True)
    pet20 = models.FloatField(null=True)
    pet21 = models.FloatField(null=True)
    pet22 = models.FloatField(null=True)
    pet23 = models.FloatField(null=True)
    pet24 = models.FloatField(null=True)

    bib15 = models.FloatField(null=True)
    bib16 = models.FloatField(null=True)
    bib17 = models.FloatField(null=True)
    bib18 = models.FloatField(null=True)
    bib19 = models.FloatField(null=True)
    bib20 = models.FloatField(null=True)
    bib21 = models.FloatField(null=True)
    bib22 = models.FloatField(null=True)
    bib23 = models.FloatField(null=True)
    bib24 = models.FloatField(null=True)

    a5l4buis15 = models.FloatField(null=True)
    a5l4buis16 = models.FloatField(null=True)
    a5l4buis17 = models.FloatField(null=True)
    a5l4buis18 = models.FloatField(null=True)
    a5l4buis19 = models.FloatField(null=True)
    a5l4buis20 = models.FloatField(null=True)
    a5l4buis21 = models.FloatField(null=True)
    a5l4buis22 = models.FloatField(null=True)
    a5l4buis23 = models.FloatField(null=True)
    a5l4buis24 = models.FloatField(null=True)

    a20lbuis15 = models.FloatField(null=True)
    a20lbuis16 = models.FloatField(null=True)
    a20lbuis17 = models.FloatField(null=True)
    a20lbuis18 = models.FloatField(null=True)
    a20lbuis19 = models.FloatField(null=True)
    a20lbuis20 = models.FloatField(null=True)
    a20lbuis21 = models.FloatField(null=True)
    a20lbuis22 = models.FloatField(null=True)
    a20lbuis23 = models.FloatField(null=True)
    a20lbuis24 = models.FloatField(null=True)

    a20lbbuis15 = models.FloatField(null=True)
    a20lbbuis16 = models.FloatField(null=True)
    a20lbbuis17 = models.FloatField(null=True)
    a20lbbuis18 = models.FloatField(null=True)
    a20lbbuis19 = models.FloatField(null=True)
    a20lbbuis20 = models.FloatField(null=True)
    a20lbbuis21 = models.FloatField(null=True)
    a20lbbuis22 = models.FloatField(null=True)
    a20lbbuis23 = models.FloatField(null=True)
    a20lbbuis24 = models.FloatField(null=True)

    a10l2buis15 = models.FloatField(null=True)
    a10l2buis16 = models.FloatField(null=True)
    a10l2buis17 = models.FloatField(null=True)
    a10l2buis18 = models.FloatField(null=True)
    a10l2buis19 = models.FloatField(null=True)
    a10l2buis20 = models.FloatField(null=True)
    a10l2buis21 = models.FloatField(null=True)
    a10l2buis22 = models.FloatField(null=True)
    a10l2buis23 = models.FloatField(null=True)
    a10l2buis24 = models.FloatField(null=True)

    abib22lbuis15 = models.FloatField(null=True)
    abib22lbuis16 = models.FloatField(null=True)
    abib22lbuis17 = models.FloatField(null=True)
    abib22lbuis18 = models.FloatField(null=True)
    abib22lbuis19 = models.FloatField(null=True)
    abib22lbuis20 = models.FloatField(null=True)
    abib22lbuis21 = models.FloatField(null=True)
    abib22lbuis22 = models.FloatField(null=True)
    abib22lbuis23 = models.FloatField(null=True)
    abib22lbuis24 = models.FloatField(null=True)

    atotalbuis15 = models.FloatField(null=True)
    atotalbuis16 = models.FloatField(null=True)
    atotalbuis17 = models.FloatField(null=True)
    atotalbuis18 = models.FloatField(null=True)
    atotalbuis19 = models.FloatField(null=True)
    atotalbuis20 = models.FloatField(null=True)
    atotalbuis21 = models.FloatField(null=True)
    atotalbuis22 = models.FloatField(null=True)
    atotalbuis23 = models.FloatField(null=True)
    atotalbuis24 = models.FloatField(null=True)

    m5l4buis15 = models.FloatField(null=True)
    m5l4buis16 = models.FloatField(null=True)
    m5l4buis17 = models.FloatField(null=True)
    m5l4buis18 = models.FloatField(null=True)
    m5l4buis19 = models.FloatField(null=True)
    m5l4buis20 = models.FloatField(null=True)
    m5l4buis21 = models.FloatField(null=True)
    m5l4buis22 = models.FloatField(null=True)
    m5l4buis23 = models.FloatField(null=True)
    m5l4buis24 = models.FloatField(null=True)

    m20lbuis15 = models.FloatField(null=True)
    m20lbuis16 = models.FloatField(null=True)
    m20lbuis17 = models.FloatField(null=True)
    m20lbuis18 = models.FloatField(null=True)
    m20lbuis19 = models.FloatField(null=True)
    m20lbuis20 = models.FloatField(null=True)
    m20lbuis21 = models.FloatField(null=True)
    m20lbuis22 = models.FloatField(null=True)
    m20lbuis23 = models.FloatField(null=True)
    m20lbuis24 = models.FloatField(null=True)

    m20lbbuis15 = models.FloatField(null=True)
    m20lbbuis16 = models.FloatField(null=True)
    m20lbbuis17 = models.FloatField(null=True)
    m20lbbuis18 = models.FloatField(null=True)
    m20lbbuis19 = models.FloatField(null=True)
    m20lbbuis20 = models.FloatField(null=True)
    m20lbbuis21 = models.FloatField(null=True)
    m20lbbuis22 = models.FloatField(null=True)
    m20lbbuis23 = models.FloatField(null=True)
    m20lbbuis24 = models.FloatField(null=True)

    m10l2buis15 = models.FloatField(null=True)
    m10l2buis16 = models.FloatField(null=True)
    m10l2buis17 = models.FloatField(null=True)
    m10l2buis18 = models.FloatField(null=True)
    m10l2buis19 = models.FloatField(null=True)
    m10l2buis20 = models.FloatField(null=True)
    m10l2buis21 = models.FloatField(null=True)
    m10l2buis22 = models.FloatField(null=True)
    m10l2buis23 = models.FloatField(null=True)
    m10l2buis24 = models.FloatField(null=True)

    mbib22lbuis15 = models.FloatField(null=True)
    mbib22lbuis16 = models.FloatField(null=True)
    mbib22lbuis17 = models.FloatField(null=True)
    mbib22lbuis18 = models.FloatField(null=True)
    mbib22lbuis19 = models.FloatField(null=True)
    mbib22lbuis20 = models.FloatField(null=True)
    mbib22lbuis21 = models.FloatField(null=True)
    mbib22lbuis22 = models.FloatField(null=True)
    mbib22lbuis23 = models.FloatField(null=True)
    mbib22lbuis24 = models.FloatField(null=True)

    mtotalbuis15 = models.FloatField(null=True)
    mtotalbuis16 = models.FloatField(null=True)
    mtotalbuis17 = models.FloatField(null=True)
    mtotalbuis18 = models.FloatField(null=True)
    mtotalbuis19 = models.FloatField(null=True)
    mtotalbuis20 = models.FloatField(null=True)
    mtotalbuis21 = models.FloatField(null=True)
    mtotalbuis22 = models.FloatField(null=True)
    mtotalbuis23 = models.FloatField(null=True)
    mtotalbuis24 = models.FloatField(null=True)

    a5l4best15 = models.FloatField(null=True)
    a5l4best16 = models.FloatField(null=True)
    a5l4best17 = models.FloatField(null=True)
    a5l4best18 = models.FloatField(null=True)
    a5l4best19 = models.FloatField(null=True)
    a5l4best20 = models.FloatField(null=True)
    a5l4best21 = models.FloatField(null=True)
    a5l4best22 = models.FloatField(null=True)
    a5l4best23 = models.FloatField(null=True)
    a5l4best24 = models.FloatField(null=True)

    a20lbest15 = models.FloatField(null=True)
    a20lbest16 = models.FloatField(null=True)
    a20lbest17 = models.FloatField(null=True)
    a20lbest18 = models.FloatField(null=True)
    a20lbest19 = models.FloatField(null=True)
    a20lbest20 = models.FloatField(null=True)
    a20lbest21 = models.FloatField(null=True)
    a20lbest22 = models.FloatField(null=True)
    a20lbest23 = models.FloatField(null=True)
    a20lbest24 = models.FloatField(null=True)

    a20lbbest15 = models.FloatField(null=True)
    a20lbbest16 = models.FloatField(null=True)
    a20lbbest17 = models.FloatField(null=True)
    a20lbbest18 = models.FloatField(null=True)
    a20lbbest19 = models.FloatField(null=True)
    a20lbbest20 = models.FloatField(null=True)
    a20lbbest21 = models.FloatField(null=True)
    a20lbbest22 = models.FloatField(null=True)
    a20lbbest23 = models.FloatField(null=True)
    a20lbbest24 = models.FloatField(null=True)

    a10l2best15 = models.FloatField(null=True)
    a10l2best16 = models.FloatField(null=True)
    a10l2best17 = models.FloatField(null=True)
    a10l2best18 = models.FloatField(null=True)
    a10l2best19 = models.FloatField(null=True)
    a10l2best20 = models.FloatField(null=True)
    a10l2best21 = models.FloatField(null=True)
    a10l2best22 = models.FloatField(null=True)
    a10l2best23 = models.FloatField(null=True)
    a10l2best24 = models.FloatField(null=True)

    abib22lbest15 = models.FloatField(null=True)
    abib22lbest16 = models.FloatField(null=True)
    abib22lbest17 = models.FloatField(null=True)
    abib22lbest18 = models.FloatField(null=True)
    abib22lbest19 = models.FloatField(null=True)
    abib22lbest20 = models.FloatField(null=True)
    abib22lbest21 = models.FloatField(null=True)
    abib22lbest22 = models.FloatField(null=True)
    abib22lbest23 = models.FloatField(null=True)
    abib22lbest24 = models.FloatField(null=True)

    atotalbest15 = models.FloatField(null=True)
    atotalbest16 = models.FloatField(null=True)
    atotalbest17 = models.FloatField(null=True)
    atotalbest18 = models.FloatField(null=True)
    atotalbest19 = models.FloatField(null=True)
    atotalbest20 = models.FloatField(null=True)
    atotalbest21 = models.FloatField(null=True)
    atotalbest22 = models.FloatField(null=True)
    atotalbest23 = models.FloatField(null=True)
    atotalbest24 = models.FloatField(null=True)

    m5l4best15 = models.FloatField(null=True)
    m5l4best16 = models.FloatField(null=True)
    m5l4best17 = models.FloatField(null=True)
    m5l4best18 = models.FloatField(null=True)
    m5l4best19 = models.FloatField(null=True)
    m5l4best20 = models.FloatField(null=True)
    m5l4best21 = models.FloatField(null=True)
    m5l4best22 = models.FloatField(null=True)
    m5l4best23 = models.FloatField(null=True)
    m5l4best24 = models.FloatField(null=True)

    m20lbest15 = models.FloatField(null=True)
    m20lbest16 = models.FloatField(null=True)
    m20lbest17 = models.FloatField(null=True)
    m20lbest18 = models.FloatField(null=True)
    m20lbest19 = models.FloatField(null=True)
    m20lbest20 = models.FloatField(null=True)
    m20lbest21 = models.FloatField(null=True)
    m20lbest22 = models.FloatField(null=True)
    m20lbest23 = models.FloatField(null=True)
    m20lbest24 = models.FloatField(null=True)

    m20lbbest15 = models.FloatField(null=True)
    m20lbbest16 = models.FloatField(null=True)
    m20lbbest17 = models.FloatField(null=True)
    m20lbbest18 = models.FloatField(null=True)
    m20lbbest19 = models.FloatField(null=True)
    m20lbbest20 = models.FloatField(null=True)
    m20lbbest21 = models.FloatField(null=True)
    m20lbbest22 = models.FloatField(null=True)
    m20lbbest23 = models.FloatField(null=True)
    m20lbbest24 = models.FloatField(null=True)

    m10l2best15 = models.FloatField(null=True)
    m10l2best16 = models.FloatField(null=True)
    m10l2best17 = models.FloatField(null=True)
    m10l2best18 = models.FloatField(null=True)
    m10l2best19 = models.FloatField(null=True)
    m10l2best20 = models.FloatField(null=True)
    m10l2best21 = models.FloatField(null=True)
    m10l2best22 = models.FloatField(null=True)
    m10l2best23 = models.FloatField(null=True)
    m10l2best24 = models.FloatField(null=True)

    mbib22lbest15 = models.FloatField(null=True)
    mbib22lbest16 = models.FloatField(null=True)
    mbib22lbest17 = models.FloatField(null=True)
    mbib22lbest18 = models.FloatField(null=True)
    mbib22lbest19 = models.FloatField(null=True)
    mbib22lbest20 = models.FloatField(null=True)
    mbib22lbest21 = models.FloatField(null=True)
    mbib22lbest22 = models.FloatField(null=True)
    mbib22lbest23 = models.FloatField(null=True)
    mbib22lbest24 = models.FloatField(null=True)

    mtotalbest15 = models.FloatField(null=True)
    mtotalbest16 = models.FloatField(null=True)
    mtotalbest17 = models.FloatField(null=True)
    mtotalbest18 = models.FloatField(null=True)
    mtotalbest19 = models.FloatField(null=True)
    mtotalbest20 = models.FloatField(null=True)
    mtotalbest21 = models.FloatField(null=True)
    mtotalbest22 = models.FloatField(null=True)
    mtotalbest23 = models.FloatField(null=True)
    mtotalbest24 = models.FloatField(null=True)