# Generated by Django 3.0.7 on 2020-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hocan15', models.FloatField()),
                ('g1sb015', models.FloatField()),
                ('corn15', models.FloatField()),
                ('hsbo15', models.FloatField()),
                ('stote_oil_blend15', models.FloatField()),
                ('chicken_par_fry15', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='graphBasedData',
        ),
    ]
