# Generated by Django 3.0.7 on 2020-07-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0011_auto_20200702_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='mpbest15',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbest16',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbest17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbest18',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbest19',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbest20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbest21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbest22',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbest23',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbest24',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis15',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis16',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis18',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis19',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis22',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis23',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='mpbuis24',
            field=models.FloatField(null=True),
        ),
    ]
