# Generated by Django 3.0.7 on 2020-07-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0018_values2'),
    ]

    operations = [
        migrations.AddField(
            model_name='values2',
            name='excprice1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='excprice2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='excprice3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='excprice4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='excprice5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='incprice1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='incprice2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='incprice3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='incprice4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='incprice5',
            field=models.FloatField(null=True),
        ),
    ]
