# Generated by Django 3.0.7 on 2020-07-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0019_auto_20200708_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='values2',
            name='tccmltlt15',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tccmltlt16',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tccmltlt17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tccmltlt18',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tccmltlt19',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tccmltlt20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tccmltlt21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tccmltlt22',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tccmltlt23',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tccmltlt24',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt15',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt16',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt18',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt19',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt22',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt23',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='tcsmltlt24',
            field=models.FloatField(null=True),
        ),
    ]
