# Generated by Django 3.0.7 on 2020-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0021_auto_20200711_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='values2',
            name='hoctotal15',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoctotal16',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoctotal17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoctotal18',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoctotal19',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoctotal20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoctotal21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoctotal22',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoctotal23',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoctotal24',
            field=models.FloatField(null=True),
        ),
    ]
