# Generated by Django 3.0.7 on 2020-07-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0022_auto_20200711_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='macd_system_total15',
            field=models.FloatField(null=True),
        ),
    ]
