# Generated by Django 3.0.7 on 2020-07-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0025_auto_20200712_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='rhpoc15',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='rhpoc16',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='rhpoc17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='rhpoc18',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='rhpoc19',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='rhpoc20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='rhpoc21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='rhpoc22',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='rhpoc23',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values',
            name='rhpoc24',
            field=models.FloatField(null=True),
        ),
    ]
