# Generated by Django 3.0.7 on 2020-07-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0028_auto_20200713_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='values2',
            name='hoil15',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoil16',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoil17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoil18',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoil19',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoil20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoil21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoil22',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoil23',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='hoil24',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil15',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil16',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil18',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil19',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil22',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil23',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='ieoil24',
            field=models.FloatField(null=True),
        ),
    ]
