# Generated by Django 3.0.7 on 2020-07-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0031_auto_20200714_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro15',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro16',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro17',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro18',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro19',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro20',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro21',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro22',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro23',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='values2',
            name='rhsbo_hydro24',
            field=models.FloatField(null=True),
        ),
    ]
