# Generated by Django 3.0.7 on 2020-07-27 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macd', '0040_auto_20200727_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='values3',
            old_name='rhpkstl_1ref',
            new_name='rhpkol_1ref',
        ),
        migrations.RenameField(
            model_name='values3',
            old_name='rhpkstl_2ref',
            new_name='rhpkol_2ref',
        ),
        migrations.RenameField(
            model_name='values3',
            old_name='rhpkstl_hydro',
            new_name='rhpkol_hydro',
        ),
        migrations.RenameField(
            model_name='values3',
            old_name='rhpkstl_loadout',
            new_name='rhpkol_loadout',
        ),
    ]
